spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1r41lxvi3po5wegbo.mysql.rds.aliyuncs.com:23123/stackside_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: dms_user_4ever
    password: Df6100+++
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3s
